FROM node:20-alpine as build-stage

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .
RUN npm run build


# Production stage
FROM node:20-alpine

WORKDIR /app

COPY --from=build-stage /app/dist /app/dist

RUN npm install -g serve

EXPOSE 8080

CMD ["serve", "-s", "dist", "-l", "8080"]
